version: '3.7'

services:
    frontend:
        container_name: ims_frontent
        build:
            context: .
            dockerfile: frontend.dockerfile.dev
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

    firebase:
        container_name: ims_firebase
        build:
            context: .
            dockerfile: firebase.dockerfile.dev
        volumes:
            - .:/opt/workspace
        ports:
            - 4000:4000
            - 9099:9099
            - 8080:8080
